[EngSys] pin http(s)-proxy-agent versions (#28568)
The latest versions broke our tests:

```
> mocha -r ../../../common/tools/esm-workaround.js -r esm --require source-map-support/register --reporter ../../../common/tools/mocha-multi-reporter.js  --reporter-option output=test-results.xml --timeout 1200000 --full-trace "dist-esm/test/internal/**/*.test.js"

/home/meng/git/jssdk/common/temp/node_modules/.pnpm/https-proxy-agent@7.0.3/node_modules/https-proxy-agent/dist/index.js:1
Error: Cannot find module 'node:url'
Require stack:
- /home/meng/git/jssdk/common/temp/node_modules/.pnpm/https-proxy-agent@7.0.3/node_modules/https-proxy-agent/dist/index.js
- /home/meng/git/jssdk/sdk/core/core-rest-pipeline/dist/index.js
- /home/meng/git/jssdk/sdk/monitor/monitor-opentelemetry-exporter/dist-esm/src/platform/nodejs/httpSender.js
...
```