[identity] upgrade dependency @azure/msal-common to ^v6.3.0 (#21739)
* [identity] upgrade dependency @azure/msal-common to ^v6.3.0

This unblocks the `rush update --full` automation. It looks that v6.3.0 has made
some change that makes v4.5.1 incompatible

```
src/msal/nodeFlows/msalNodeCommon.ts(270,7): error TS2322: Type 'import("/mnt/vss/_work/1/s/common/temp/node_modules/.pnpm/@azure+msal-common@4.5.1/node_modules/@azure/msal-common/dist/account/AccountInfo").AccountInfo' is not assignable to type 'import("/mnt/vss/_work/1/s/common/temp/node_modules/.pnpm/@azure+msal-common@6.3.0/node_modules/@azure/msal-common/dist/account/AccountInfo").AccountInfo'.
  Types of property 'idTokenClaims' are incompatible.
    Type 'object | undefined' is not assignable to type '(TokenClaims & { [key: string]: unknown; }) | undefined'.
      Type 'object' is not assignable to type 'TokenClaims & { [key: string]: unknown; }'.
        Type 'object' is not assignable to type '{ [key: string]: unknown; }'.
          Index signature for type 'string' is missing in type '{}'.
```

* update recordings

newer version of msal-common includes response_type=token%20id_token in request body