[EngSys] pin transitive dep pg-protocol version to 1.8.0
as the latest 1.9.5 version cause build error:

>../../../common/temp/node_modules/.pnpm/@types+pg@8.6.1/node_modules/@types/pg/index.d.ts(12,31): error TS2307: Cannot find module 'pg-protocol/dist/messages' or its corresponding type declarations.

we will need to wait for a fix from either @types/pg or pg-protocol.