[KeyVault] - Fix JavaScript samples and poller circular references (#15735)
## What

- Remove unnecessary `export` from KV samples
- Fix circular dependency in KV pollers

## Why

I noticed today that the keyvault-secrets samples were failing to run due to 

```
SyntaxError: Unexpected token 'export'
```

There's an existing bug against dev-tool (#15724) which when fixed will address this, but in order to make sure
our samples are working it's perfectly fine not to export these functions.

Fixing the circular dependencies is a good thing to do before we go out.