in browser, the error caught doesn't have message property!
AssertionError: expecting valid error.message but error is [object CloseEvent]: expected undefined to be truthy