test(@azure/core-amqp): Remove invalid port specifier from emulator connection tests
Using the `sb::/h:port` Endpoint syntax is invalid, the underlying connection socket library doesn't support specifying the port in the host field.
https://nodejs.org/api/net.html#socketconnectport-host-connectlistener
```
ServiceBusError: ENOTFOUND: getaddrinfo ENOTFOUND localhost:5681
```