[EngSys] fix CI build error
of

>src/multiVersion.ts(8,7): error TS2503: Cannot find namespace 'Mocha'.

`test-utils` is missing dev dependency `@types/mocha`. Previously other packages
installed it and `test-utils` was able to "share"