[dev-tool] Inline dynamic imports in browser bundle
Because `umd` doesn't support dynamic imports and rollup will give errors like:

>RollupError: Invalid value "umd" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.

This error showed up in rush automation runs where we upgraded to msal-browser 3.3.0
which started using `await import`.

This PR uses `inlineDynamicImports: true` for browser bundle.