[engsys] pin vitest and @vitest/browser version to 1.1.3 (#28255)
as core-util browser testing is broken by 1.2.0 with the following error

https://github.com/vitest-dev/vitest/issues/4984

```
 FAIL  test/public/aborterUtils.spec.ts > createAbortablePromise > should resolve if not aborted nor rejected
ReferenceError: process is not defined
 ❯ test/public/aborterUtils.spec.ts:30:21
     28|
     29|   it("should resolve if not aborted nor rejected", async function () {
     30|     const clock = vi.useFakeTimers();
       |                     ^
     31|     const promise = createPromise();
     32|     await clock.advanceTimersToNextTimerAsync();
```