[test-utils] Fix package.json to include all types (#29626)
### Packages impacted by this PR

- @azure-tools/test-utils

### Issues associated with this PR


### Describe the problem that is addressed by this PR

The types were not properly being exported hence the following error
messages:

```
../../../common/temp/node_modules/.pnpm/@azure-tools+test-utils@1.0.0/node_modules/@azure-tools/test-utils/types/src/index.d.ts(1,108): error TS2307: Cannot find module './multiVersion' or its corresponding type declarations.
  ...12 lines omitted...
../../../common/temp/node_modules/.pnpm/@azure-tools+test-utils@1.0.0/node_modules/@azure-tools/test-utils/types/src/index.d.ts(14,42): error TS2307: Cannot find module './tracing/mockContext' or its corresponding type declarations.
test/public/browser/usernamePasswordCredential.spec.ts(9,10): error TS2305: Module '"@azure-tools/test-utils"' has no exported member 'fakeTestPasswordPlaceholder'.
test/public/node/azureApplicationCredential.spec.ts(56,14): error TS7006: Parameter 'tracingOptions' implicitly has an 'any' type.
test/public/node/clientCertificateCredential.spec.ts(113,14): error TS7006: Parameter 'tracingOptions' implicitly has an 'any' type.
test/public/node/clientSecretCredential.spec.ts(84,14): error TS7006: Parameter 'tracingOptions' implicitly has an 'any' type.
test/public/node/deviceCodeCredential.spec.ts(168,14): error TS7006: Parameter 'tracingOptions' implicitly has an 'any' type.
test/public/node/environmentCredential.spec.ts(125,14): error TS7006: Parameter 'tracingOptions' implicitly has an 'any' type.
test/public/node/environmentCredential.spec.ts(146,14): error TS7006: Parameter 'tracingOptions' implicitly has an 'any' type.
test/public/node/environmentCredential.spec.ts(164,14): error TS7006: Parameter 'tracingOptions' implicitly has an 'any' type.
test/public/node/usernamePasswordCredential.spec.ts(86,14): error TS7006: Parameter 'tracingOptions' implicitly has an 'any' type.
```

### What are the possible designs available to address the problem? If
there are more than one possible design, why was the one in this PR
chosen?


### Are there test cases added in this PR? _(If not, why?)_


### Provide a list of related PRs _(if any)_


### Command used to generate this PR:**_(Applicable only to SDK release
request PRs)_

### Checklists
- [ ] Added impacted package name to the issue description
- [ ] Does this PR needs any fixes in the SDK Generator?** _(If so,
create an Issue in the
[Autorest/typescript](https://github.com/Azure/autorest.typescript)
repository and link it here)_
- [ ] Added a changelog (if necessary)