[engsys] prepare for TypeScript v5 (#25429)
- dev-tool: react to removal of TS deprecated Modifier api
- eslint-plugin: react to removal of TS deprecated Modifier api
- communication-network-traversal: remove redundant code. `options`
already has a default value of `{}`. Use `...` to make a copy
- form-recognizer: fix compile error of 
>test/public/training.spec.ts(236,28): error TS2339: Property 'message'
does not exist on type 'unknown'.
- identity: fix compile error of 
>../identity/src/msal/utils.ts(229,5): error TS2322: Type 'string |
undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
- perf-tests/core-reset-pipeline: downgrade to @types/node ^16.0.0 for
now. In v17 the new properties in AbortSignal type is causing error

>../../../../common/temp/node_modules/.pnpm/@types+node@17.0.45/node_modules/@types/node/globals.d.ts(72,13):
error TS2403: Subsequent variable declarations must have the same type.
Variable 'AbortSignal' must be of type '{ new (): AbortSignal;
prototype: AbortSignal; abort(reason?: any): AbortSignal;
timeout(milliseconds: number): AbortSignal; }', but here has type '{ new
(): AbortSignal; prototype: AbortSignal; }'.