[storage][test] fix integration by double-quoting file patterns (#32584)
The recent Mocha upgrades broke storage integration tests on Windows,
likely due to their upgrade of yargs dependency. With single quotes, we
now get errors like

>Error: No test files found:
"'dist-esm/storage-file-share/test/**/*.spec.js'"

This PR changes to use escaped doubled quotes in the scripts.