Add lock file for generate-doc tool (#31789)
A recent package update broke the tool so we are adding a lock file to
ensure we have a reliable execution.

For details the newer version of
https://www.npmjs.com/package/shiki?activeTab=versions version 1.23.0
introduced a new dependency in https://github.com/shikijs/shiki/pull/832
which no longer compiles.

```
node_modules/oniguruma-to-es/types/parse.d.ts(61,49): error TS2339: Property 'orphan' does not exist on type '{}'.
node_modules/oniguruma-to-es/types/parse.d.ts(96,31): error TS2339: Property 'atomic' does not exist on type '{}'.
node_modules/oniguruma-to-es/types/parse.d.ts(96,39): error TS2339: Property 'flags' does not exist on type '{}'.
```

Until we figure out what the best way to fix those issues we are pinning
to the older version using a lock file.