[Recorder] improve error messages (#21575)
Properly handle recorder errors due to mismatches etc., and pretty-print the error messages to make debugging easier.

Old error message format (example):

```
RestError: {"Message":"Unable to find a record for the request 
POST https://fakeaccountname.table.core.windows.net/Tables?st=2021-08-03T08:52:15Z\u0026spr=https\u0026sig=fakesigval\n
Header differences:\n \u003CConnection\u003E is absent in record, value \u003Ckeep-alive\u003E\n
Body differences:\n","Status":"NotFound"}
```

New error message format (different example, but note that it's a lot more legible):

```
RecorderError: Unable to find a record for the request DELETE https://myregistry.azurecr.io/v2/oci-artifact/manifests/sha256%3A70e2ffca8e79adc4bd34b67363a972522d75933e435084826d39a19f958579ed
Uri doesn't match:
    request <https://myregistry.azurecr.io/v2/oci-artifact/manifests/sha256%3A70e2ffca8e79adc4bd34b67363a972522d75933e435084826d39a19f958579ed>
    record  <https://myregistry.azurecr.io/v2/oci-artifact/manifests/sha256%3Ad5dd4479d4b658f68b10a47e51815472f3313dc7886ec17a1744deb21dc186f4>
Header differences:
Body differences:
```