[core-http] add missing dev dependency @rollup/plugin-replace (#15082)
to fix build error:

    [!] Error: Cannot find module '@rollup/plugin-replace'