[ServiceBus] Fix linter errors and enable linting (#18670)
* [ServiceBus] Enable linting

* Fixing most linting errors in tests

* Fix more linting errors in src

* Disable errors

- for namespace
- parameter of `any`

* make key const and value mutable

* Add `.catch()` block for promise

* address CR feedback

* format

* Delete test input of undefined ruleOptions for createRule() test

* Use different overloads of `crateRule()`

* Update to the new rule name

* in browser, the error caught doesn't have message property!

AssertionError: expecting valid error.message but error is [object CloseEvent]: expected undefined to be truthy