Fix browser build due to new generated pkgVersion code
The error was
```
@azure/storage-file-datalake:test:browser: [build-test] Building for browser testing...
@azure/storage-file-datalake:test:browser: src/generated/api/dataLakeContext.ts(5,21): error TS6307: File '/mnt/vss/_work/1/s/sdk/storage/storage-file-datalake/dist/browser/package.json' is not listed within the file list of project '/mnt/vss/_work/1/s/sdk/storage/storage-file-datalake/tsconfig.browser.config.json'. Projects must list all files or use an 'include' pattern.
@azure/storage-file-datalake:test:browser: src/generated/api/dataLakeContext.ts(27,67): error TS2339: Property 'version' does not exist on type '{ type: string; }'.
@azure/storage-file-datalake:test:browser: [build-test] TypeScript compilation failed for tsconfig.browser.config.json (exit code 1). See the tsc errors above.
@azure/storage-file-datalake:test:browser: [dev-tool] Errors occurred. See the output above.
@azure/storage-file-datalake:test:browser: [ELIFECYCLE] Command failed with exit code 1.
```