update test recording for browser test
Difference in how special characters are escaped in xml body payload

### playback error

```
RecorderError: Unable to find a record for the request POST https://Sanitized.queue.core.windows.net/queue171445970488109569/messages?visibilitytimeout=0&messagettl=40&timeout=30
Header differences:
Body differences:
Request and record bodies do not match at index 106:
     request: "_+`-=[]|};&apos;&quot;:,./?&gt"
     record:  "_+`-=[]|};'":,./?&gt;&lt;`~æ¼¢"
```

This is because for browser we now also use fast-xml-parser (same as nodejs).  There's slight difference in how some special characters are escaped (or not).   The end results are the same though as nodejs and browser tests are both passing in live test runs.

### tests (1):

- QueueClient message methods > enqueue, peek, dequeue special characters