keyvault-admin: update abort tests to verify error message
likely due to vitest/chai changes, the tests are failing in pnpm PR with the
following error:

```
AssertionError: expected error to be instance of AbortError

- Expected:
[Function AbortError]

+ Received:
AbortError {
  "message": "The operation was aborted. Request has already been canceled.",
  "name": "AbortError",
}
```